const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
let Processor;
const code = fs.readFileSync('assets/local_pcm_playout_processor.js','utf8');
vm.runInNewContext(code, {
  AudioWorkletProcessor: class { constructor() { this.port={postMessage:m=>this.last=m}; } },
  Float32Array, Uint8Array, DataView, Number, Math,
  registerProcessor: (_, p) => Processor=p,
});
const source = new Processor();
let id=0;
const send = (type,extra={}) => {source.port.onmessage({data:{id:++id,generation:1,epoch:0,type,...extra}});return source.last;};
const render = () => {const out=[new Float32Array(128),new Float32Array(128)];source.process([],[out]);return out;};
assert.equal(send('start').error,undefined);
const pcm=new Uint8Array(48000);new DataView(pcm.buffer).setInt16(0,-32768,true);
assert.equal(send('write',{pcm}).error,undefined);
const impulse=render();
assert.deepEqual(impulse[0],impulse[1]);
assert.equal(impulse[0][32],-1);
assert.equal(send('state').state.consumedFrames,64);
for(let i=0;i<4;i++)assert.equal(send('write',{pcm}).error,undefined);
const queued=send('state').state.queuedFrames;
assert.match(send('write',{pcm}).error,/backlog/);
assert.equal(send('state').state.queuedFrames,queued);
assert.equal(send('clear',{epoch:1}).error,undefined);
assert.equal(send('state').state.queuedFrames,0);
assert.equal(render()[0].every(v=>v===0),true);
assert.match(send('write',{pcm}).error,/epoch/);
assert.match(send('write',{generation:2,epoch:1,pcm}).error,/generation/);
assert.match(send('write',{epoch:1,pcm:new Uint8Array(3)}).error,/Invalid/);
assert.equal(send('write',{epoch:1,pcm}).error,undefined);
assert.equal(send('stop').error,undefined);
assert.equal(source.sources.size,0);
assert.match(send('write',{epoch:1,pcm}).error,/generation/);
assert.equal(render()[0].every(v=>v===0),true);
assert.match(send('start').error,/generation/);
const start=(generation,sampleRate,channels)=>send('start',{generation,sampleRate,channels,ownershipMode:'shared'});
assert.equal(start(2,24000,1).error,undefined);
assert.equal(start(3,48000,2).error,undefined);
assert.match(start(4,24000,1).error,/capacity/);
assert.match(send('start',{generation:4}).error,/owned/);
const constant=(frames,values)=>{
 const bytes=new Uint8Array(frames*values.length*2),view=new DataView(bytes.buffer);
 for(let i=0;i<frames;i++)for(let c=0;c<values.length;c++)view.setInt16((i*values.length+c)*2,values[c],true);
 return bytes;
};
assert.match(send('write',{generation:3,pcm:new Uint8Array(2)}).error,/Invalid/);
assert.equal(send('write',{generation:2,pcm:constant(1000,[1000])}).error,undefined);
assert.equal(send('write',{generation:3,pcm:constant(2000,[2000,-1000])}).error,undefined);
let mix=render();
assert.ok(Math.abs(mix[0][100]*32768-3000)<1);
assert.ok(Math.abs(mix[1][100]*32768)<1);
assert.equal(send('state',{generation:2}).state.consumedFrames,64);
assert.equal(send('state',{generation:3}).state.consumedFrames,128);
send('clear',{generation:2,epoch:1});
mix=render();
assert.equal(mix[0][100]*32768,2000);
assert.equal(mix[1][100]*32768,-1000);
send('stop',{generation:2});
assert.equal(send('state',{generation:3}).state.generation,3);
assert.equal(start(4,24000,1).error,undefined);
send('clear',{generation:3,epoch:1});
send('write',{generation:3,epoch:1,pcm:constant(2000,[32767,16000])});
send('write',{generation:4,pcm:constant(1000,[32767])});
mix=render();
assert.ok(mix.every(ch=>ch.every(v=>Math.abs(v)<=1)));
assert.ok(mix[0][100]>mix[1][100]);
send('stop',{generation:3});send('stop',{generation:4});
assert.equal(source.sources.size,0);
const dart=fs.readFileSync('lib/src/web/local_pcm_playout_processor_source.dart','utf8');
assert.equal(dart.split("r'''\n")[1].split("''';")[0],code);
console.log('PASS: stereo mix, mono resampling, independent owners, bounds, limiter, stale tokens, embedded source');
